HRApplyApp/HRApplyApp.UI/Models/PoliciesByCategoryVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HrApplyApp.Models;

namespace HRApplyApp.UI.Models
{
    public class PoliciesByCategoryVM
    {

        public List<Policy> Policies { get; set; }
        public List<Policy> AllPolicies { get; set; }
        public string Category { get; set; }
        public List<PolicyCategory> Polcatlist { get; set; }
        public List<SelectListItem> SelectCategories { get; set; }

        public List<Policy> CreatePolicyList(string cat)
        {
            List<Policy> pollist = new List<Policy>();
            pollist = pollist.Where(p => p.Category == cat).ToList();
            return pollist;
        }

        public List<SelectListItem> CreateCategorySelectList(string cat)
        {
            List<PolicyCategory> polcatlist = new List<PolicyCategory>();
            polcatlist = polcatlist.Where(p => p.PolicyCategoryName == cat).ToList();
            List<SelectListItem> polcatsellist = new List<SelectListItem>();
            foreach (var p in polcatlist)
            {
                var newItem = new SelectListItem();
                newItem.Text = p.PolicyCategoryName;

                polcatsellist.Add(newItem);
            }
            return polcatsellist;

        }
    }
}

HRApplyApp/HRApplyApp.UI/Models/TimeVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HrApplyApp.Models;

namespace HRApplyApp.UI.Models
{
    public class TimeVM
    {
        public List<SelectListItem> Employees { get; set; }
        public decimal HoursWorked { get; set; }
        [DataType(DataType.Date)]
        public DateTime DayWorked { get; set; }

        public TimeVM(List<Employee> employees)
        {
            Employees = new List<SelectListItem>();

            foreach (var emp in employees)
            {
                var se = new SelectListItem();

                se.Text = emp.LastName + ", " + emp.FirstName;
                se.Value = emp.EmpID.ToString();

                Employees.Add(se);
            }
        }
    }
}

HRApplyApp/HRApplyApp.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HrApplyApp.Models;
using HRApplyApp.Data;

namespace HRApplyApp.UI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Resume newResume)
        {
            newResume.DateofApplication = DateTime.Now;
            var repo = new ResumeRepository();
            repo.RootPath = Server.MapPath("~/");
            repo.Add(newResume);
            
            if (ModelState.IsValid)
            {
            return View("Result", newResume);
            }

            return View();
        }


        public ActionResult Result2()
        {
            return View("Result2");
        }

        public ActionResult Admin()
        {
            var repo = new ResumeRepository();
            repo.RootPath = Server.MapPath("~/");
            var resumes = repo.GetAll();

            return View(resumes);
        }
    }
}

HRApplyApp/HRApplyApp.UI/Controllers/PoliciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HrApplyApp.Models;
using HRApplyApp.Data;
using HRApplyApp.UI.Models;

namespace HRApplyApp.UI.Controllers
{
    public class PoliciesController : Controller
    {
        // GET: Policies
        public ActionResult Index()
        {
            var repo = new PolicyRepository();
            repo.RootPath = Server.MapPath("~/");
            var pvm = new PoliciesByCategoryVM();
            pvm.AllPolicies = repo.GetAll();
            pvm.Polcatlist = repo.GetAllPolicyCategories();

            return View("Index", pvm);
        }

        [HttpPost]
        public ActionResult AddPolicy()
        {
            var p = new Policy();

            p.PolicyName = Request.Form["Name"];
            p.PolicyDescription = Request.Form["Description"];
            p.Category = Request.Form["Category"];

            var repo = new PolicyRepository();
            repo.RootPath = Server.MapPath("~/");
            repo.Add(p);

            return RedirectToAction("Manage");
        }

        public ActionResult Manage()
        {
            var repo = new PolicyRepository();
            repo.RootPath = Server.MapPath("~/");
            var policies = repo.GetAll();
            return View(policies);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var repo = new PolicyRepository();
            repo.RootPath = Server.MapPath("~/");
            var policy = repo.GetPolicyById(id);

            repo.Delete(policy.PolicyID);

            return RedirectToAction("Manage");
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            var repo = new PolicyRepository();
            repo.RootPath = Server.MapPath("~/");
            var pol = repo.GetPolicyById(id);
            return View(pol);
        }

        [HttpPost]
        public ActionResult EditPolicy(int id)
        {
            Policy policy = new Policy();
            policy.PolicyID = int.Parse(Request.Form["id"]);
            policy.PolicyName = Request.Form["Name"];
            policy.PolicyDescription = Request.Form["Description"];
            policy.Category = Request.Form["Category"];

            var repo = new PolicyRepository();
            repo.RootPath = Server.MapPath("~/");
            repo.Edit(policy);

            return RedirectToAction("Manage");
        }

        [HttpPost]
        public ActionResult PoliciesByCategory(PoliciesByCategoryVM pvm)
        {
            var repo = new PolicyRepository {RootPath = Server.MapPath("~/")};
            pvm.Policies = repo.GetAll().Where(p=>p.Category == pvm.Category).ToList();

            return View(pvm);
        }

        public ActionResult ManageCategory(PoliciesByCategoryVM pvm)
        {
            var repo = new PolicyRepository { RootPath = Server.MapPath("~/") };
            pvm.Polcatlist = repo.GetAllPolicyCategories();

            return View(pvm);
        }
    }
}

HRApplyApp/HRApplyApp.UI/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HrApplyApp.Models;
using HRApplyApp.Data;
using HRApplyApp.UI.Models;

namespace HRApplyApp.UI.Controllers
{
    public class TimeController : Controller
    {
        // GET: Time
        public ActionResult Index()
        {
            var repo = new EmployeeRepository();
            var employeeList = repo.GetAll();
            var vm =  new TimeVM(employeeList);

            return View(vm);
        }

        [HttpPost]
        public ActionResult SubmitTime(TimeRecord record)
        {
            if (ModelState.IsValid)
            {
                var repo = new EmployeeRepository();
                repo.AddTimeRecordToDB(record);

                return RedirectToAction("TimeSheet");
            }
            return RedirectToAction("Index");
        }

        public ActionResult TimeSheet()
        {
            var repo = new EmployeeRepository();
            var timeRecords = repo.GetTimeRecords();
            var employeeList = repo.GetAll();
            foreach (var employee in employeeList)
            {
                employee.TimeRecords = new List<TimeRecord>();

                foreach (var timeRecord in timeRecords.Where(timeRecord => timeRecord.EmpID == employee.EmpID))
                {
                    employee.TimeRecords.Add(timeRecord);
                    employee.TimeRecords = employee.TimeRecords.OrderBy(s=>s.DateWorked).ToList();
                }
            }

            return View(employeeList);
        }
    }
}

HRApplyApp/HRApplyApp.UI/Views/Home/Admin.cshtml
@model List<HrApplyApp.Models.Resume>

@{
    ViewBag.Title = "Admin";
}

<br />
<h2>Admin</h2>
<br />
<h4>List of Applications</h4>

<div class="container">
    <div class="row">
            <div class="col-md-2 col-xs-3">
                <h6>ID</h6>
            </div>
            <div class="col-md-2 col-xs-3">
                <h6>First Name</h6>
            </div>
            <div class="col-md-2 col-xs-3">
                <h6>Last Name</h6>
            </div>
        <div class="col-md-2 col-xs-3">
            <h6>Email</h6>
        </div>
    </div>
@foreach (var resume in Model)
{
    <div class="row">
        <div class="panel panel-primary">
            <div class="col-md-2 col-xs-3">
                <br />
                <p>@resume.ApplicantId</p>
            </div>
            <div class="col-md-2 col-xs-3">
                <br />
                <p>@resume.FirstName</p>
            </div>
            <div class="col-md-2 col-xs-3">
                <br />
                <p>@resume.LastName</p>
            </div>
            <div class="col-md-2 col-xs-6">
                <br />
                <p>@resume.Email</p>
            </div>
            <div class="col-md-2 col-xs-6">
                    <button id="moreinfo" class="btn btn-danger btn-sm" type="button" data-toggle="collapse" data-target="#viewdetails_@resume.ApplicantId" aria-expanded="false" aria-controls="collapseExample">
                        More Info
                    </button>
            </div>
        </div>
    </div>
    <div class="collapse" id="viewdetails_@resume.ApplicantId">
        <div class="well">
            <div class="row">
                <div class="col-xs-4">
                    <h6>Street Address</h6>
                    <p>@resume.StreetAddress</p>
                </div>
                <div class="col-xs-4">
                    <h6>City</h6>
                    <p>@resume.City</p>
                </div>
                <div class="col-xs-4">
                    <h6>State</h6>
                    <p>@resume.State</p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <h6>Country</h6>
                    <p>@resume.Country</p>
                </div>
                <div class="col-xs-4">
                    <h6>Zip Code</h6>
                    <p>@resume.Zipcode</p>
                </div>
                <div class="col-xs-4">
                    <h6>Phone #</h6>
                    <p>@resume.PhoneNumber</p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <h6>Skype</h6>
                    <p>@resume.SkypeName</p>
                </div>
                <div class="col-xs-4">
                    <h6>Work History</h6>
                    <p>@resume.WorkHistory</p>
                </div>
                <div class="col-xs-4">
                    <h6>Education</h6>
                    <p>@resume.Education</p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <h6>Position Applying For</h6>
                    <p>@resume.Position</p>
                </div>
                <div class="col-xs-4">
                    <h6>Desired Salary</h6>
                    <p>@resume.Salary</p>
                </div>
                <div class="col-xs-4">
                    <h6>Application Date</h6>
                    <p>@resume.DateofApplication</p>
                </div>
            </div>
        </div>
    </div>
}

</div>

@section Admin {
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("HR Apply App", "Index", "Home", new { area = "" })</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("View Policies", "Index", "Policies")</li>
                    <li>@Html.ActionLink("Manage Policies", "Manage", "Policies")</li>
                    <li>@Html.ActionLink("Manage Categories", "ManageCategory", "Policies")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracking <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Submit Time", "Index", "Time")</li>
                    <li>@Html.ActionLink("View Timesheet", "TimeSheet", "Time")</li>
                </ul>
            </li>
            <li>@Html.ActionLink("Admin", "Admin", "Home", new { area = "" }, null)</li>
        </ul>
    </div>

}

HRApplyApp/HRApplyApp.UI/Views/Home/Result2.cshtml
@model HrApplyApp.Models.Resume

@{
    ViewBag.Title = "Result2";
}

<br />
<h2>Straight into the garbage bin</h2>

@Html.ActionLink("Return to Index", "Index", "Home")

@Html.DisplayForModel(Model)

HRApplyApp/HRApplyApp.UI/Views/Policies/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>
<div>
    <h1>Add Policy</h1>
    <h3>@Html.ActionLink("Back to list", "Manage", "Policies")</h3>
    <form action="/Policies/AddPolicy" method="POST">
        <p>
            <label>Name</label>
            <input type="text" id="Name" name="Name"/>
        </p>
        <p>
            <label>Description</label>
            <input type="text" id="Description" name="Description"/>
        </p>
        <p>
            <label>Category</label>
            <input type="text" id="Category" name="Category"/>
        </p>
        <button class="btn btn-primary">Save</button>
    </form>
</div>


@section Admin {
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("HR Apply App", "Index", "Home", new { area = "" })</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("View Policies", "Index", "Policies")</li>
                    <li>@Html.ActionLink("Manage Policies", "Manage", "Policies")</li>
                    <li>@Html.ActionLink("Manage Categories", "ManageCategory", "Policies")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracking <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Submit Time", "Index", "Time")</li>
                    <li>@Html.ActionLink("View Timesheet", "TimeSheet", "Time")</li>
                </ul>
            </li>
            <li>@Html.ActionLink("Admin", "Admin", "Home", new { area = "" }, null)</li>
        </ul>
    </div>

}

HRApplyApp/HRApplyApp.UI/Views/Policies/Edit.cshtml
@model HrApplyApp.Models.Policy

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<div>
    <h1>Edit Policy</h1>
    <h3>@Html.ActionLink("Back to list", "Manage", "Policies")</h3>
    <form action="/Policies/EditPolicy" method="POST">
        <p>
            <label>Name</label>
            <input type="text" id="Name" name="Name"/>
        </p>
        <p>
            <label>Description</label>
            <textarea type="text" id="Description" name="Description"></textarea>
        </p>
        <p>
            <label>Category</label>
            <input type="text" id="Category" name="Category"/>
        </p>
        //@Html.Hidden("id", Model.PolicyID);
        <button class="btn btn-primary">Save</button>
    </form>
</div>


@section Admin {
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("HR Apply App", "Index", "Home", new { area = "" })</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("View Policies", "Index", "Policies")</li>
                    <li>@Html.ActionLink("Manage Policies", "Manage", "Policies")</li>
                    <li>@Html.ActionLink("Manage Categories", "ManageCategory", "Policies")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracking <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Submit Time", "Index", "Time")</li>
                    <li>@Html.ActionLink("View Timesheet", "TimeSheet", "Time")</li>
                </ul>
            </li>
            <li>@Html.ActionLink("Admin", "Admin", "Home", new { area = "" }, null)</li>
        </ul>
    </div>

}

HRApplyApp/HRApplyApp.UI/Views/Policies/Index.cshtml
@model HRApplyApp.UI.Models.PoliciesByCategoryVM

@{
    ViewBag.Title = "Index";
}

<h2>View Policies</h2>
<br/>

@foreach (var pol in Model.AllPolicies.ToList())
{
    <p>Name : @pol.PolicyName</p>
    <p>Description : @pol.PolicyDescription</p>
    <p>Category : @pol.Category</p>
    <hr/>
}

<h2>View policies by category:</h2>
<br />
<div class="row">
    @*drop down here*@
    @using (Html.BeginForm("PoliciesByCategory", "Policies", FormMethod.Post))
    {
        @Html.DropDownListFor(m => m.Category, new SelectList(Model.Polcatlist, "PolicyCategoryName", "PolicyCategoryName"), "Select a category")
        <button class="btn btn-danger">View policies</button>
    }
</div>

@section Admin {
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("HR Apply App", "Index", "Home", new { area = "" })</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("View Policies", "Index", "Policies")</li>
                    <li>@Html.ActionLink("Manage Policies", "Manage", "Policies")</li>
                    <li>@Html.ActionLink("Manage Categories", "ManageCategory", "Policies")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracking <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Submit Time", "Index", "Time")</li>
                    <li>@Html.ActionLink("View Timesheet", "TimeSheet", "Time")</li>
                </ul>
            </li>
            <li>@Html.ActionLink("Admin", "Admin", "Home", new { area = "" }, null)</li>
        </ul>
    </div>

}

HRApplyApp/HRApplyApp.UI/Views/Policies/Manage.cshtml
@model List<HrApplyApp.Models.Policy>

@{
    ViewBag.Title = "Manage";
}

<br/>
<h2>Manage Policies</h2>
<br/>

    @foreach (var pol in Model)
    {
        <div class="container">
            <div class="row">
                <div class="col-md-offset-2 col-md-6 col-xs-12">
                    <br />
                    <h3>Name : @pol.PolicyName</h3>
                    <p>Description : @pol.PolicyDescription</p>
                    <p>Category : @pol.Category</p>
                    @*<p>@Html.ActionLink("Edit", "Edit", "Policies", new { id = @pol.PolicyID }, null)</p>*@
                </div>
                    <div class="col-md-2 margin-top-20">
                        @using (Html.BeginForm("Edit", "Policies", FormMethod.Post))
                        {
                            @Html.Hidden("id", pol.PolicyID)
                            <input type="hidden" name="PolicyID" id="PolicyID" value="@pol.PolicyID" />
                            <button class="btn btn-danger">Edit</button>
                        }


                        @using (Html.BeginForm("Delete", "Policies", FormMethod.Post))
                        {
                            @Html.Hidden("id", pol.PolicyID)
                            <input type="hidden" name="PolicyID" id="PolicyID" value="@pol.PolicyID" />
                            <button class="btn btn-danger">Delete</button>
                        }
                    </div>
            </div>
            <hr />
        </div>
    }
@*<p>@Html.ActionLink("Add", "Add", "Policies")</p>*@
@using (Html.BeginForm("Add", "Policies", FormMethod.Post))
{
    <button class="btn btn-primary">Add new policy</button>
}


@section Admin {
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("HR Apply App", "Index", "Home", new { area = "" })</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("View Policies", "Index", "Policies")</li>
                    <li>@Html.ActionLink("Manage Policies", "Manage", "Policies")</li>
                    <li>@Html.ActionLink("Manage Categories", "ManageCategory", "Policies")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracking <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Submit Time", "Index", "Time")</li>
                    <li>@Html.ActionLink("View Timesheet", "TimeSheet", "Time")</li>
                </ul>
            </li>
            <li>@Html.ActionLink("Admin", "Admin", "Home", new { area = "" }, null)</li>
        </ul>
    </div>

}

HRApplyApp/HRApplyApp.UI/Views/Policies/ManageCategory.cshtml
@model HRApplyApp.UI.Models.PoliciesByCategoryVM

@{
    ViewBag.Title = "ManageCategory";
}

<h2>Choose a category to manage:</h2>

@using (Html.BeginForm("PoliciesByCategory", "Policies", FormMethod.Post))
{
    @Html.DropDownListFor(m => m.Category, new SelectList(Model.Polcatlist, "PolicyCategoryName", "PolicyCategoryName"), "Select a category")
    <button class="btn btn-danger">View policies in this category</button>
}

@section Admin {
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("HR Apply App", "Index", "Home", new { area = "" })</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("View Policies", "Index", "Policies")</li>
                    <li>@Html.ActionLink("Manage Policies", "Manage", "Policies")</li>
                    <li>@Html.ActionLink("Manage Categories", "ManageCategory", "Policies")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracking <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Submit Time", "Index", "Time")</li>
                    <li>@Html.ActionLink("View Timesheet", "TimeSheet", "Time")</li>
                </ul>
            </li>
            <li>@Html.ActionLink("Admin", "Admin", "Home", new { area = "" }, null)</li>
        </ul>
    </div>

}

HRApplyApp/HRApplyApp.UI/Views/Policies/PoliciesByCategory.cshtml
@model HRApplyApp.UI.Models.PoliciesByCategoryVM

@{
    ViewBag.Title = "PoliciesByCategory";
}

<h2>Policies under Category @Model.Category</h2>

@foreach (var pol in Model.Policies)
{
    <p>Policy Name : @pol.PolicyName</p>
    <p>Policy Description : @pol.PolicyDescription</p>
    <p>Policy Category : @pol.Category</p>
}


@section Admin {
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("HR Apply App", "Index", "Home", new { area = "" })</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("View Policies", "Index", "Policies")</li>
                    <li>@Html.ActionLink("Manage Policies", "Manage", "Policies")</li>
                    <li>@Html.ActionLink("Manage Categories", "ManageCategory", "Policies")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracking <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Submit Time", "Index", "Time")</li>
                    <li>@Html.ActionLink("View Timesheet", "TimeSheet", "Time")</li>
                </ul>
            </li>
            <li>@Html.ActionLink("Admin", "Admin", "Home", new { area = "" }, null)</li>
        </ul>
    </div>

}

HRApplyApp/HRApplyApp.UI/Views/Time/Index.cshtml
@using System.Web.UI.WebControls
@model HRApplyApp.UI.Models.TimeVM

@{
    ViewBag.Title = "Index";
}

<h2>Time Management</h2>

@using (Html.BeginForm("SubmitTime", "Time", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <div class="row">
        <div class="form-group">
            <label class="label label-default">Select Employee</label>
            @Html.DropDownList("EmpID", Model.Employees, "(select)", new {@class = "dropdown", @id = "inputEmployee"})
        </div>
        <div class="form-group">
            <label class="label label-default">Day Worked</label>
            <input id="theDate" type="text" name="DateWorked"/>
        </div>
        <div class="form-group">
            <label class="label label-default">Hours Worked</label>
            <input id="hoursWorkedInputField" type="number" step="any" min="0" max="16" name="HoursWorked"/>
        </div>
        <button class="btn btn-primary">Submit</button>
    </div>
}

@section Admin {
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("HR Apply App", "Index", "Home", new { area = "" })</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("View Policies", "Index", "Policies")</li>
                    <li>@Html.ActionLink("Manage Policies", "Manage", "Policies")</li>
                    <li>@Html.ActionLink("Manage Categories", "ManageCategory", "Policies")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time Tracking <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Submit Time", "Index", "Time")</li>
                    <li>@Html.ActionLink("View Timesheet", "TimeSheet", "Time")</li>
                </ul>
            </li>
            <li>@Html.ActionLink("Admin", "Admin", "Home", new { area = "" }, null)</li>
        </ul>
    </div>

}

@section Scripts{
    <script src="/Scripts/jquery-ui-1.10.2.min.js"></script>
    <script src="/Scripts/app/datePicker.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
}